#!/bin/bash

source /usr/lib/rsp/desktop/startRspDesktopWaylandEnv;

#/usr/local/bin/pcmanfm-qt --desktop --platform xcb &
#/usr/local/bin/rsp-panel --platform xcb &
#/usr/local/bin/rsp-panel --platform xcb --config "$HOME"/.config/rsp/panel-xcb.conf &
#/usr/local/bin/nm-applet;

exec /usr/local/bin/rsp-session;