#!/bin/bash

source /usr/lib/rsp/desktop/startRspDesktop-env;

# /usr/local/bin/rsp-globalkeysd --no-daemon &
# /usr/local/bin/rsp-notificationd --platform xcb &
# /usr/local/bin/rsp-policykit-agent  --platform xcb &
/usr/local/bin/pcmanfm-qt --desktop --platform xcb &
/usr/local/bin/rsp-panel --platform xcb &

sleep 1;

## Commands to run on desktop start
/usr/lib/rsp/startRspDesktop-run &

sleep 1;

## Desktop GUI apps on desktop start
/usr/lib/rsp/desktop/startRspDesktop-start;
