#!/bin/bash

export GTK_CSD=0
export LD_PRELOAD="/usr/local/lib/libgtk3-nocsd.so.0"
export LD_LIBRARY_PATH="/usr/local/lib:/usr/lib";

export WM="compify"
export WINDOW_MANAGER="compify"

export GDK_BACKEND="x11"
export MOZ_ENABLE_WAYLAND="1"
export BEMENU_BACKEND="wayland"
export CLUTTER_BACKEND="wayland"
export SDL_VIDEODRIVER="wayland"

export XDG_MENU_PREFIX="rsp-"
export XDG_CURRENT_DESKTOP="RSp"
export XDG_SESSION_DESKTOP="RSp"

export XDG_SESSION_TYPE="wayland"
export XKB_DEFAULT_RULES="evdev"






export QT_QPA_PLATFORMTHEME="qt6ct"

export _JAVA_AWT_WM_NONREPARENTING=1